# Generated by Django 4.1 on 2022-08-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('second_name', models.CharField(max_length=300)),
                ('old_password', models.CharField(max_length=300)),
                ('new_password', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=60)),
            ],
        ),
    ]
